{% set name = "llvmlite" %}
{% set version = "0.37.0" %}
{% set sha256 = "6392b870cd018ec0c645d6bbb918d6aa0eeca8c62674baaee30862d6b6865b15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # don't use github generated tar-ball as the sha256 value may not be stable
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-add_dll_directory-for-LIBRARY_BIN-for-Py38-on-Windows.patch  # [win and py>=38]

build:
  number: 1
  skip: true  # [py<37]
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                   # [unix]
  host:
    - python
    - llvmdev 11.1.*
    - llvm 11.1.*
    - zlib
    - vs2015_runtime  # [win]
  run:
    - python
    - zlib
    - vs2015_runtime  # [win]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
