{% set name = "llvmlite" %}
{% set version = "0.44.0" %}
{% set sha256 = "07667d66a5d150abed9157ab6c0b9393c9356f229784a4385c02f99e94fc94d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # don't use github generated tar-ball as the sha256 value may not be stable
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <4
    - make                   # [unix]
  host:
    - python
    - setuptools
    - llvmdev 15.0.*        # abstract pin for static lib
    - llvmdev 15.0.7 *_5    # concrete pin for static lib - bot should update
    - zlib
  run:
    - python

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
    - beckermr
    - esc
