{% set name = "llvmlite" %}
{% set version = "0.44.0rc1" %}
{% set sha256 = "3b9f00270f2a4a09756e0d1f505894e76ef3a55df960fddbcfa5687569fd1a9e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/numba/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<310]
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                   # [unix]
  host:
    - python
    - setuptools
    - llvmdev 15.0.*
    - llvm 15.0.*
    - zlib
    - vs2015_runtime  # [win]
  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
