{% set name = "llvmlite" %}
{% set version = "0.40.1" %}
{% set sha256 = "5cdb0d45df602099d833d50bd9e81353a5e036242d3c003c5b294fc61d1986b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # don't use github generated tar-ball as the sha256 value may not be stable
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<37]
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                   # [unix]
  host:
    - python
    - setuptools
    - llvmdev 14.0.*
    - llvm 14.0.*
    - zlib
    - vs2015_runtime  # [win]
  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
