{% set name = "llvmlite" %}
{% set version = "0.28.0" %}
{% set sha256 = "a189c0cd8a80e8bbd002a1e422b1efcc2bceab2cb63b961f2d03ab711c3ba45b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # don't use github generated tar-ball as the sha256 value may not be stable
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script_env:
    - PY_VCRUNTIME_REDIST    # [win]
  skip: true  # [win and py==27]

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [linux or (win and py==27)]
    - {{ compiler('cxx') }}  # [linux or (win and py==27)]
    - vs2017_win-64          # [win64 and py>27]
    - vs2017_win-32          # [win32 and py>27]
    # The DLL build uses cmake on Windows
    - cmake                  # [win]
    - make                   # [unix]
  host:
    - python
    - llvmdev 7.0.*
    - enum34          # [py27]
    # llvmdev is built with libz compression support
    - zlib            # [unix]
  run:
    - python
    - enum34          # [py27]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1  # [osx]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - souravsingh
