{% set name = "llvmlite" %}
{% set version = "0.41.skiporcjit" %}
{% set sha256 = "50f89226d2c208c6d24ef157af79fdc0cf5f7eb12bae9f568537ed1b5cc9a930" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gmarkall/llvmlite/archive/refs/tags/0.41-skip-orcjit.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<37]
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                   # [unix]
  host:
    - python
    - setuptools
    - llvmdev 14.0.*
    - llvm 14.0.*
    - zlib
    - vs2015_runtime  # [win]
  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
