{% set name = "llvmlite" %}
{% set version = "0.26.0" %}
{% set sha256 = "13e84fe6ebb0667233074b429fd44955f309dead3161ec89d9169145dbad2ebf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script_env:
    - PY_VCRUNTIME_REDIST
#  ignore_run_exports:
#    - vs2017_win-64  # [win64]
#    - vs2017_win-32  # [win32]
#    - vc

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [linux or (win and py==27)]
    - {{ compiler('cxx') }}  # [linux or (win and py==27)]
    - vs2017_win-64          # [win64 and py>27]
    - vs2017_win-32          # [win32 and py>27]
    # The DLL build uses cmake on Windows
    - cmake                  # [win]
    - make                   # [unix]
  host:
    - python
    # On channel https://anaconda.org/numba/
    - llvmdev 6.0*
    - vs2015_runtime  # [win]
    - enum34          # [py27]
    # llvmdev is built with libz compression support
    - zlib            # [unix]
  run:
    - python
    - enum34          # [py27]
    - vs2015_runtime  # [win]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1  # [osx]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - souravsingh
