{% set name = "llvmlite" %}
{% set version = "0.45.1" %}
{% set sha256 = "09430bb9d0bb58fc45a45a57c7eae912850bedc095cd0810a57de109c69e1c32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # don't use github generated tar-ball as the sha256 value may not be stable
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake <4
    - make                   # [unix]
  host:
    - python
    - setuptools
    - llvmdev 20.*        # abstract pin for static lib
    - llvmdev 20.1.8 *_1  # concrete pin for static lib - bot should update
    - zlib
    - zstd
  run:
    - python

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
    - beckermr
    - esc
