{% set name = "llvmlite" %}
{% set version = "0.33.0" %}
{% set sha256 = "9c8aae96f7fba10d9ac864b443d1e8c7ee4765c31569a2b201b3d0b67d8fc596" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # don't use github generated tar-ball as the sha256 value may not be stable
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: patch_cmake.patch  # [win]

build:
  number: 0
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}            # [unix]
    - {{ compiler('cxx') }}          # [unix]
    - vs2017_{{ target_platform }}   # [win]
    # The DLL build uses cmake on Windows
    - cmake                  # [win]
    - make                   # [unix]
    - zlib  # [win]
  host:
    - python
    - llvmdev 9.0.1
    - zlib
  run:
    - python
    - llvmdev 9.0.1

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
