schema_version: 1

context:
  build_number: 1
  name: "llvmlite"
  version: "0.49.0"
  llvm_version: "22.1.8 *_1"  # concrete pin for static lib - maintainer should update?

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 00f16db782f4a13c78c5804aedc434e46794a77e89999a168f9401106270e50a

build:
  number: ${{ build_number }}
  script:
    content:
      - ${{ 'export CFLAGS="${CFLAGS/-fno-plt/}" CXXFLAGS="${CXXFLAGS/-fno-plt/}"' if ppc64le else "" }}
      - ${{ 'export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"' if "osx" in target_platform else "" }}
      - ${{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .
    env:
      LLVMLITE_ENABLE_ZLIB: "ON"
      LLVMLITE_SHARED: 0
      LLVMLITE_USE_CMAKE: 1

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake <4
    - if: unix
      then:
        - make
  host:
    - pip
    - python
    - setuptools
    - llvmdev ${{ llvm_version | split('.') | first }}.*
    - llvmdev ==${{ llvm_version }}
    - zlib
    - zstd
  run:
    - python

tests:
  - package_contents:
      strict: true
      files:
        - ${{ "lib/python*" if unix else "Lib" }}/site-packages/llvmlite-0.49.0.dist-info/*
        - ${{ "lib/python*" if unix else "Lib" }}/site-packages/llvmlite/*
  - python:
      imports:
        - llvmlite
        - llvmlite.binding
      pip_check: true
  - script:
      - python -m llvmlite.tests

about:
  homepage: http://llvmlite.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  documentation: http://llvmlite.pydata.org/
  repository: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
    - beckermr
    - esc
    - MementoRC
