appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: OWMwDl9ensIqnBlNxRkrWKzPhMWBXjT83AyArrjytsTTczCb/fc8JNIETPOq/d8Xc3fOv01cWIex1L2j827jOJvexvYgi8cjIRkzU+t5DAQfgBCuBSy5fwHLw2BefxpgZ/A+HtBiE834m85S/Yu+O20URD8N3FztHyFfToZIo3MI+vRD/mMrYkF6wLSPcJLni7v3tp1/VHPKRu9fvC5w1XbSPqJVWtdnaDd3EgrkjdPNTT3VAn8MmcykmBa0wjPnk21aqTmrFxn5MPOJRTv7niK1nVjWHBE2EKkC1yYFepJRDZV5vg9cYfkam2KHuncfdeey24Igfn6s3V/FMG2znNrBuGZ7k2a3QwKgEcwXXrkCyZ7FHu6unGsVpl3EWCYJc3qToAvXJxDIpf31SO8lwZ6aOq6OTBte6S3DL+EIk4m+xzYc1iOAFsBEcyEjLGkPvB5Vp/AsnOQBPUP1k+6tpjIR/wDSRFkglYmoLuswZAVRyC0OVM+b1siGFA/SfC7YzW3lrpXH3ewWZCKbFSZsJRDkbeRINehpkOAwdHdBCKsodCVfmEbsPknICWQ1IXQK8veuNUrP8ZYOktQ1RbmYWbdUkzFre7w8ww/Z9NQSSM7SlZF7eo1alEhGqYVKBaf2Eygmpu5vcI1cfr2Lllo0m7tcq/toT/QYNY9MN3bxOB0=}
